# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: default
  labels:
    app: mcp-server
spec:
  selector:
    matchLabels:
      app: mcp-server
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  mcp-server
      labels:
        app: mcp-server
    spec:
      containers:
      - name: mcp-server
        image: ko://github.com/Cali0707/AutoMCP/cmd/mcp-server
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: http
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: default
spec:
  selector:
    app: mcp-server
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---


